In [1]:
# import pandas as pd
# data={
#     "calories":[420,569,546]
#     "duration":[568,653,754]
# df=pd.DataFrame(data)
# print(df)

In [2]:
import pandas as pd
df=pd.read_csv('statsfinal.csv')
print(df.head(10))

   Unnamed: 0        Date  Q-P1  Q-P2  Q-P3  Q-P4      S-P1      S-P2  \
0           0  13-06-2010  5422  3725   576   907  17187.74  23616.50   
1           1  14-06-2010  7047   779  3578  1574  22338.99   4938.86   
2           2  15-06-2010  1572  2082   595  1145   4983.24  13199.88   
3           3  16-06-2010  5657  2399  3140  1672  17932.69  15209.66   
4           4  17-06-2010  3668  3207  2184   708  11627.56  20332.38   
5           5  18-06-2010  2898  2539   311  1513   9186.66  16097.26   
6           6  19-06-2010  6912  1470  1576  1608  21911.04   9319.80   
7           7  20-06-2010  5209  2550  3415   842  16512.53  16167.00   
8           8  21-06-2010  6322   852  3646  1377  20040.74   5401.68   
9           9  22-06-2010  6865   414  3902   562  21762.05   2624.76   

       S-P3      S-P4  
0   3121.92   6466.91  
1  19392.76  11222.62  
2   3224.90   8163.85  
3  17018.80  11921.36  
4  11837.28   5048.04  
5   1685.62  10787.69  
6   8541.92  11465.04  
7  1

In [3]:
print(df.tail())

      Unnamed: 0        Date  Q-P1  Q-P2  Q-P3  Q-P4      S-P1      S-P2  \
4595        4595  30-01-2023  2476  3419   525  1359   7848.92  21676.46   
4596        4596  31-01-2023  7446   841  4825  1311  23603.82   5331.94   
4597        4597  01-02-2023  6289  3143  3588   474  19936.13  19926.62   
4598        4598  02-02-2023  3122  1188  5899   517   9896.74   7531.92   
4599        4599  03-02-2023  1234  3854  2321   406   3911.78  24434.36   

          S-P3     S-P4  
4595   2845.50  9689.67  
4596  26151.50  9347.43  
4597  19446.96  3379.62  
4598  31972.58  3686.21  
4599  12579.82  2894.78  


In [4]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  4600 non-null   int64  
 1   Date        4600 non-null   object 
 2   Q-P1        4600 non-null   int64  
 3   Q-P2        4600 non-null   int64  
 4   Q-P3        4600 non-null   int64  
 5   Q-P4        4600 non-null   int64  
 6   S-P1        4600 non-null   float64
 7   S-P2        4600 non-null   float64
 8   S-P3        4600 non-null   float64
 9   S-P4        4600 non-null   float64
dtypes: float64(4), int64(5), object(1)
memory usage: 359.5+ KB
None


In [5]:
df.isnull().sum()

Unnamed: 0    0
Date          0
Q-P1          0
Q-P2          0
Q-P3          0
Q-P4          0
S-P1          0
S-P2          0
S-P3          0
S-P4          0
dtype: int64

In [6]:
df.describe()

Unnamed: 0         Q-P1         Q-P2         Q-P3         Q-P4  \
count  4600.000000  4600.000000  4600.000000  4600.000000  4600.000000   
mean   2299.500000  4121.849130  2130.281522  3145.740000  1123.500000   
std    1328.049949  2244.271323  1089.783705  1671.832231   497.385676   
min       0.000000   254.000000   251.000000   250.000000   250.000000   
25%    1149.750000  2150.500000  1167.750000  1695.750000   696.000000   
50%    2299.500000  4137.000000  2134.000000  3202.500000  1136.500000   
75%    3449.250000  6072.000000  3070.250000  4569.000000  1544.000000   
max    4599.000000  7998.000000  3998.000000  6000.000000  2000.000000   

               S-P1          S-P2          S-P3          S-P4  
count   4600.000000   4600.000000   4600.000000   4600.000000  
mean   13066.261743  13505.984848  17049.910800   8010.555000  
std     7114.340094   6909.228687   9061.330694   3546.359869  
min      805.180000   1591.340000   1355.000000   1782.500000  
25%     6817.085000   7403.535000   9190.965000   4962.480000  
50%    13114.290000  13529.560000  17357.550000   8103.245000  
75%    19248.240000  19465.385000  24763.980000  11008.720000  
max    25353.660000  25347.320000  32520.000000  14260.000000

In [7]:
df.columns

Index(['Unnamed: 0', 'Date', 'Q-P1', 'Q-P2', 'Q-P3', 'Q-P4', 'S-P1', 'S-P2',
       'S-P3', 'S-P4'],
      dtype='object')

In [8]:
df.isnull().sum()

Unnamed: 0    0
Date          0
Q-P1          0
Q-P2          0
Q-P3          0
Q-P4          0
S-P1          0
S-P2          0
S-P3          0
S-P4          0
dtype: int64

In [9]:
print(df["Date"].unique())

['13-06-2010' '14-06-2010' '15-06-2010' ... '01-02-2023' '02-02-2023'
 '03-02-2023']


In [10]:
print(df["Unnamed: 0"].unique())

[   0    1    2 ... 4597 4598 4599]


In [11]:
print(df["Q-P1"].unique())

[5422 7047 1572 ... 1227 3122 1234]


In [12]:
print(df["S-P3"].unique())

[ 3121.92 19392.76  3224.9  ... 26151.5  19446.96 31972.58]


In [13]:
print(df["S-P4"].unique())

[ 6466.91 11222.62  8163.85 ...  8277.93  8206.63  7928.56]


In [14]:
df.dropna()

Unnamed: 0        Date  Q-P1  Q-P2  Q-P3  Q-P4      S-P1      S-P2  \
0              0  13-06-2010  5422  3725   576   907  17187.74  23616.50   
1              1  14-06-2010  7047   779  3578  1574  22338.99   4938.86   
2              2  15-06-2010  1572  2082   595  1145   4983.24  13199.88   
3              3  16-06-2010  5657  2399  3140  1672  17932.69  15209.66   
4              4  17-06-2010  3668  3207  2184   708  11627.56  20332.38   
...          ...         ...   ...   ...   ...   ...       ...       ...   
4595        4595  30-01-2023  2476  3419   525  1359   7848.92  21676.46   
4596        4596  31-01-2023  7446   841  4825  1311  23603.82   5331.94   
4597        4597  01-02-2023  6289  3143  3588   474  19936.13  19926.62   
4598        4598  02-02-2023  3122  1188  5899   517   9896.74   7531.92   
4599        4599  03-02-2023  1234  3854  2321   406   3911.78  24434.36   

          S-P3      S-P4  
0      3121.92   6466.91  
1     19392.76  11222.62  
2      3224.90   8163.85  
3     17018.80  11921.36  
4     11837.28   5048.04  
...        ...       ...  
4595   2845.50   9689.67  
4596  26151.50   9347.43  
4597  19446.96   3379.62  
4598  31972.58   3686.21  
4599  12579.82   2894.78  

[4600 rows x 10 columns]

In [15]:
df.dropna(axis=1)

Unnamed: 0        Date  Q-P1  Q-P2  Q-P3  Q-P4      S-P1      S-P2  \
0              0  13-06-2010  5422  3725   576   907  17187.74  23616.50   
1              1  14-06-2010  7047   779  3578  1574  22338.99   4938.86   
2              2  15-06-2010  1572  2082   595  1145   4983.24  13199.88   
3              3  16-06-2010  5657  2399  3140  1672  17932.69  15209.66   
4              4  17-06-2010  3668  3207  2184   708  11627.56  20332.38   
...          ...         ...   ...   ...   ...   ...       ...       ...   
4595        4595  30-01-2023  2476  3419   525  1359   7848.92  21676.46   
4596        4596  31-01-2023  7446   841  4825  1311  23603.82   5331.94   
4597        4597  01-02-2023  6289  3143  3588   474  19936.13  19926.62   
4598        4598  02-02-2023  3122  1188  5899   517   9896.74   7531.92   
4599        4599  03-02-2023  1234  3854  2321   406   3911.78  24434.36   

          S-P3      S-P4  
0      3121.92   6466.91  
1     19392.76  11222.62  
2      3224.90   8163.85  
3     17018.80  11921.36  
4     11837.28   5048.04  
...        ...       ...  
4595   2845.50   9689.67  
4596  26151.50   9347.43  
4597  19446.96   3379.62  
4598  31972.58   3686.21  
4599  12579.82   2894.78  

[4600 rows x 10 columns]

In [16]:
import pandas as pd
import numpy as np
data={
    "calories":[420,569,546,np.nan],
    "duration":[568,653,754,np.nan]}
df1=pd.DataFrame(data)
df1

calories  duration
0     420.0     568.0
1     569.0     653.0
2     546.0     754.0
3       NaN       NaN

In [17]:
df1.dropna()

calories  duration
0     420.0     568.0
1     569.0     653.0
2     546.0     754.0

In [18]:
df1['calories'].fillna(569,inplace=True)

C:\Users\Diyanjali\AppData\Local\Temp\ipykernel_27256\3428487060.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['calories'].fillna(569,inplace=True)


In [19]:
df1

calories  duration
0     420.0     568.0
1     569.0     653.0
2     546.0     754.0
3     569.0       NaN

In [20]:
df1

calories  duration
0     420.0     568.0
1     569.0     653.0
2     546.0     754.0
3     569.0       NaN

In [21]:
df1

calories  duration
0     420.0     568.0
1     569.0     653.0
2     546.0     754.0
3     569.0       NaN

In [22]:
df1['duration'].fillna(df1['duration'].mean(),inplace=True)

C:\Users\Diyanjali\AppData\Local\Temp\ipykernel_27256\3260998566.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['duration'].fillna(df1['duration'].mean(),inplace=True)


In [23]:
df1

calories    duration
0     420.0  568.000000
1     569.0  653.000000
2     546.0  754.000000
3     569.0  658.333333

In [24]:
df1.drop_duplicates()

calories    duration
0     420.0  568.000000
1     569.0  653.000000
2     546.0  754.000000
3     569.0  658.333333

In [25]:
df1

calories    duration
0     420.0  568.000000
1     569.0  653.000000
2     546.0  754.000000
3     569.0  658.333333

In [26]:
df1['duration']=df1['duration'].astype(int)

In [27]:
df1

calories  duration
0     420.0       568
1     569.0       653
2     546.0       754
3     569.0       658

In [33]:
# df['Date'] = pd.to_datetime(df['Date'], dayfirst=True, errors='coerce')


In [35]:
df

Unnamed: 0       Date  Q-P1  Q-P2  Q-P3  Q-P4      S-P1      S-P2  \
0              0 2010-06-13  5422  3725   576   907  17187.74  23616.50   
1              1 2010-06-14  7047   779  3578  1574  22338.99   4938.86   
2              2 2010-06-15  1572  2082   595  1145   4983.24  13199.88   
3              3 2010-06-16  5657  2399  3140  1672  17932.69  15209.66   
4              4 2010-06-17  3668  3207  2184   708  11627.56  20332.38   
...          ...        ...   ...   ...   ...   ...       ...       ...   
4595        4595 2023-01-30  2476  3419   525  1359   7848.92  21676.46   
4596        4596 2023-01-31  7446   841  4825  1311  23603.82   5331.94   
4597        4597 2023-02-01  6289  3143  3588   474  19936.13  19926.62   
4598        4598 2023-02-02  3122  1188  5899   517   9896.74   7531.92   
4599        4599 2023-02-03  1234  3854  2321   406   3911.78  24434.36   

          S-P3      S-P4  
0      3121.92   6466.91  
1     19392.76  11222.62  
2      3224.90   8163.85  
3     17018.80  11921.36  
4     11837.28   5048.04  
...        ...       ...  
4595   2845.50   9689.67  
4596  26151.50   9347.43  
4597  19446.96   3379.62  
4598  31972.58   3686.21  
4599  12579.82   2894.78  

[4600 rows x 10 columns]

In [37]:
df.rename(columns={'Unnamed: 0':'Name'},inplace=True)

In [39]:
df

Name       Date  Q-P1  Q-P2  Q-P3  Q-P4      S-P1      S-P2      S-P3  \
0        0 2010-06-13  5422  3725   576   907  17187.74  23616.50   3121.92   
1        1 2010-06-14  7047   779  3578  1574  22338.99   4938.86  19392.76   
2        2 2010-06-15  1572  2082   595  1145   4983.24  13199.88   3224.90   
3        3 2010-06-16  5657  2399  3140  1672  17932.69  15209.66  17018.80   
4        4 2010-06-17  3668  3207  2184   708  11627.56  20332.38  11837.28   
...    ...        ...   ...   ...   ...   ...       ...       ...       ...   
4595  4595 2023-01-30  2476  3419   525  1359   7848.92  21676.46   2845.50   
4596  4596 2023-01-31  7446   841  4825  1311  23603.82   5331.94  26151.50   
4597  4597 2023-02-01  6289  3143  3588   474  19936.13  19926.62  19446.96   
4598  4598 2023-02-02  3122  1188  5899   517   9896.74   7531.92  31972.58   
4599  4599 2023-02-03  1234  3854  2321   406   3911.78  24434.36  12579.82   

          S-P4  
0      6466.91  
1     11222.62  
2      8163.85  
3     11921.36  
4      5048.04  
...        ...  
4595   9689.67  
4596   9347.43  
4597   3379.62  
4598   3686.21  
4599   2894.78  

[4600 rows x 10 columns]

In [41]:
filtered_df=df[df['Q-P2']>1000]

In [43]:
df

Name       Date  Q-P1  Q-P2  Q-P3  Q-P4      S-P1      S-P2      S-P3  \
0        0 2010-06-13  5422  3725   576   907  17187.74  23616.50   3121.92   
1        1 2010-06-14  7047   779  3578  1574  22338.99   4938.86  19392.76   
2        2 2010-06-15  1572  2082   595  1145   4983.24  13199.88   3224.90   
3        3 2010-06-16  5657  2399  3140  1672  17932.69  15209.66  17018.80   
4        4 2010-06-17  3668  3207  2184   708  11627.56  20332.38  11837.28   
...    ...        ...   ...   ...   ...   ...       ...       ...       ...   
4595  4595 2023-01-30  2476  3419   525  1359   7848.92  21676.46   2845.50   
4596  4596 2023-01-31  7446   841  4825  1311  23603.82   5331.94  26151.50   
4597  4597 2023-02-01  6289  3143  3588   474  19936.13  19926.62  19446.96   
4598  4598 2023-02-02  3122  1188  5899   517   9896.74   7531.92  31972.58   
4599  4599 2023-02-03  1234  3854  2321   406   3911.78  24434.36  12579.82   

          S-P4  
0      6466.91  
1     11222.62  
2      8163.85  
3     11921.36  
4      5048.04  
...        ...  
4595   9689.67  
4596   9347.43  
4597   3379.62  
4598   3686.21  
4599   2894.78  

[4600 rows x 10 columns]

In [45]:
df=df[['Q-P1','S-P1']]

In [47]:
df

Q-P1      S-P1
0     5422  17187.74
1     7047  22338.99
2     1572   4983.24
3     5657  17932.69
4     3668  11627.56
...    ...       ...
4595  2476   7848.92
4596  7446  23603.82
4597  6289  19936.13
4598  3122   9896.74
4599  1234   3911.78

[4600 rows x 2 columns]

In [53]:
df1['sum']=df1['calories']+df1['duration']

In [55]:
df1

calories  duration     sum
0     420.0       568   988.0
1     569.0       653  1222.0
2     546.0       754  1300.0
3     569.0       658  1227.0

In [57]:
df1.to_csv("pandas.csv", index=False)